// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_pages_DeepDive from "./routes/(pages)/DeepDive.tsx";
import * as $_pages_EditScenario from "./routes/(pages)/EditScenario.tsx";
import * as $_pages_Overview from "./routes/(pages)/Overview.tsx";
import * as $_pages_RunBatch from "./routes/(pages)/RunBatch.tsx";
import * as $_pages_layout from "./routes/(pages)/_layout.tsx";
import * as $_pages_index from "./routes/(pages)/index.tsx";
import * as $DeepDiveMap from "./islands/DeepDiveMap.tsx";
import * as $DeepDiveSidebar from "./islands/DeepDiveSidebar.tsx";
import * as $EditScenarioMap from "./islands/EditScenarioMap.tsx";
import * as $EditScenarioModal from "./islands/EditScenarioModal.tsx";
import * as $EditScenarioSidebar from "./islands/EditScenarioSidebar.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $OverviewMap from "./islands/OverviewMap.tsx";
import * as $OverviewSidebar from "./islands/OverviewSidebar.tsx";
import * as $RunBatchMoe from "./islands/RunBatchMoe.tsx";
import * as $RunBatchSidebar from "./islands/RunBatchSidebar.tsx";
import * as $ScenarioDetails from "./islands/ScenarioDetails.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(pages)/DeepDive.tsx": $_pages_DeepDive,
    "./routes/(pages)/EditScenario.tsx": $_pages_EditScenario,
    "./routes/(pages)/Overview.tsx": $_pages_Overview,
    "./routes/(pages)/RunBatch.tsx": $_pages_RunBatch,
    "./routes/(pages)/_layout.tsx": $_pages_layout,
    "./routes/(pages)/index.tsx": $_pages_index,
  },
  islands: {
    "./islands/DeepDiveMap.tsx": $DeepDiveMap,
    "./islands/DeepDiveSidebar.tsx": $DeepDiveSidebar,
    "./islands/EditScenarioMap.tsx": $EditScenarioMap,
    "./islands/EditScenarioModal.tsx": $EditScenarioModal,
    "./islands/EditScenarioSidebar.tsx": $EditScenarioSidebar,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/OverviewMap.tsx": $OverviewMap,
    "./islands/OverviewSidebar.tsx": $OverviewSidebar,
    "./islands/RunBatchMoe.tsx": $RunBatchMoe,
    "./islands/RunBatchSidebar.tsx": $RunBatchSidebar,
    "./islands/ScenarioDetails.tsx": $ScenarioDetails,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
