// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_pages_layout from "./routes/(pages)/_layout.tsx";
import * as $_pages_index from "./routes/(pages)/index.tsx";
import * as $DeepDive from "./islands/DeepDive.tsx";
import * as $DeepDiveMap from "./islands/DeepDiveMap.tsx";
import * as $DeepDiveSidebar from "./islands/DeepDiveSidebar.tsx";
import * as $EditScenario from "./islands/EditScenario.tsx";
import * as $EditScenarioMap from "./islands/EditScenarioMap.tsx";
import * as $EditScenarioSidebar from "./islands/EditScenarioSidebar.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $Overview from "./islands/Overview.tsx";
import * as $OverviewMap from "./islands/OverviewMap.tsx";
import * as $OverviewSidebar from "./islands/OverviewSidebar.tsx";
import * as $RunBatch from "./islands/RunBatch.tsx";
import * as $RunBatchMoe from "./islands/RunBatchMoe.tsx";
import * as $RunBatchSidebar from "./islands/RunBatchSidebar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(pages)/_layout.tsx": $_pages_layout,
    "./routes/(pages)/index.tsx": $_pages_index,
  },
  islands: {
    "./islands/DeepDive.tsx": $DeepDive,
    "./islands/DeepDiveMap.tsx": $DeepDiveMap,
    "./islands/DeepDiveSidebar.tsx": $DeepDiveSidebar,
    "./islands/EditScenario.tsx": $EditScenario,
    "./islands/EditScenarioMap.tsx": $EditScenarioMap,
    "./islands/EditScenarioSidebar.tsx": $EditScenarioSidebar,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/Overview.tsx": $Overview,
    "./islands/OverviewMap.tsx": $OverviewMap,
    "./islands/OverviewSidebar.tsx": $OverviewSidebar,
    "./islands/RunBatch.tsx": $RunBatch,
    "./islands/RunBatchMoe.tsx": $RunBatchMoe,
    "./islands/RunBatchSidebar.tsx": $RunBatchSidebar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
